#!/usr/bin/env bash

config=releng

rm -rf $config
cp -r "${isopath:-/usr/share/archiso/configs/$config}" ./

cd $config

cat ../pkgs >> packages.x86_64
sed -i 's/^linux$/linux-lts/g' packages.x86_64

cat <<'EOF' >> pacman.conf
[archzfs]
SigLevel = Required
Server = https://github.com/archzfs/archzfs/releases/download/experimental
EOF

find . -type f -exec sed -i 's/vmlinuz-linux/vmlinuz-linux-lts/g' {} \;
find . -type f -exec sed -i 's/initramfs-linux/initramfs-linux-lts/g' {} \;

# ssh setup

mkdir airootfs/root/.ssh
cat ~/.ssh/keys/archiso.pub >> airootfs/root/.ssh/authorized_keys

sed -i '$d' profiledef.sh
cat <<EOF >> profiledef.sh
  ["/root/.ssh"]="0:0:0700"
  ["/root/.ssh/authorized_keys"]="0:0:0600"
)
EOF
